language: node_js
node_js:
  - ">=8.0.0"
sudo: false
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
